name: Build and Push Container

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Podman
      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      # Build the container
      - name: Build container image
        run: |
          podman build -t my-app:latest .

  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Podman
      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      # Log in to ghcr.io
      - name: Log in to GitHub Container Registry
        run: echo "$GITHUB_TOKEN" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      # Tag and Push the container image
      - name: Tag and push container
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            podman tag my-app:latest $IMAGE_NAME:main
            podman push $IMAGE_NAME:main
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
            podman tag my-app:latest $IMAGE_NAME:$TAG
            podman push $IMAGE_NAME:$TAG
          fi

  pr-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Podman
      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      # Build the container image for PRs
      - name: Build container image
        run: |
          podman build -t my-app-pr:latest .
